version: "3.9"
services:
  nginx:
    build: ./nginx/
    ports:
      - 8008:80

    volumes:
      - ./public/:/var/www/html/

  php:
    container_name: reservation-system
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/myapp
      - ./composer.json:/usr/src/myapp/composer.json